version: '3.7'

services:
  consul-server:
    image: hashicorp/consul:1.10.0
    restart: always
    volumes:
      - ./consul-server.json:/consul/config/server.json:ro
      - ./consul-demo:/consul/data
    networks:
      - demo
    ports:
      - "8500:8500"
    command: "agent"

  vault:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    networks:
      - demo
    depends_on:
      - consul-server
    cap_add:
      - CAP_IPC_LOCK
    command: "server"
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_LOCAL_CONFIG: >-
        {
          "backend":{
              "consul":{
                  "address":"consul-server:8500",
                  "path":"vault/"}
              },
              "listener":{
                  "tcp":{
                      "address":"0.0.0.0:8200",
                      "tls_disable":1
                  }
              },
              "ui":true,
              "log_level":"trace"
          }
        }

networks:
  demo:
    driver: bridge